name: Build LaTeX document

on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.5.2
        with:
          files: |
            **/*.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          working_directory: ./en
          root_file: ./thesis.tex
          texlive_version: 2021

      - name: Move PDF to a separate directory
        if: steps.changed-files.outputs.any_changed == 'true'
        run: mkdir -p ./dist && mv ./en/thesis.pdf ./dist/bar-social-network-analysis-in-academic-environment-2024.pdf

      - name: Setup Pages
        if: github.ref == 'refs/heads/main' && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main' && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
    
  deploy-files:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check if artifact exists
        id: artifact
        run: echo ::set-output name=exists::$(test -f ./dist/bar-social-network-analysis-in-academic-environment-2024.pdf && echo true || echo false)

      - name: Deploy to GitHub Pages
        if: steps.artifact.outputs.exists == 'true'
        id: deployment
        uses: actions/deploy-pages@v2